sudo: required
services:
    - docker

before_install:
    - docker build -t bumeranghc/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true bumeranghc/react-test npm test

after_success:
    - docker build -t bumeranghc/multi-client ./client
    - docker build -t bumeranghc/multi-nginx ./nginx
    - docker build -t bumeranghc/multi-server ./server
    - docker build -t bumeranghc/multi-worker ./worker
    # Log in to the Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to Docker Hub
    - docker push bumeranghc/multi-client
    - docker push bumeranghc/multi-nginx
    - docker push bumeranghc/multi-server
    - docker push bumeranghc/multi-worker
